# Generated by Django 5.0.7 on 2024-08-31 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.CharField(default='test', max_length=50),
            preserve_default=False,
        ),
    ]
