# Generated by Django 5.0.7 on 2024-08-28 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='emoji',
        ),
    ]
